=== noushadali/osgi-samples/branches/cr-version-1/cr-registerparticipant-webservice/WS-INF/CongressRegistration.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema
		xmlns="http://dispatcher.congress.osgisamples.com"
		xmlns:xs="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://dispatcher.congress.osgisamples.com"
		elementFormDefault="unqualified" attributeFormDefault="unqualified">
	<xs:element name="CongressRegistrationRequest">
		<xs:complexType>
			<xs:sequence minOccurs="1">
				<xs:element ref="Congress" />
				<xs:element ref="Registrant" />
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="CongressRegistrationResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="RegistrationCode" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Congress">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="CongressId"/>
				<xs:element ref="CongressName"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="CongressName">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="25"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="CongressId">
		<xs:simpleType>
			<xs:restriction base="xs:int"/>
		</xs:simpleType>
	</xs:element>

	<xs:element name="Registrant">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="FirstName"/>
				<xs:element ref="MiddleName" maxOccurs="1" minOccurs="0"/>
				<xs:element ref="LastName"/>
				<xs:element ref="Email"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="FirstName">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="25"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="MiddleName">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="15"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="LastName">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="75"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="Email">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="100"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="RegistrationCode">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="50"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== noushadali/osgi-samples/branches/cr-nljug-jspring2007/cr-xml-interface/src/test/resources/CongressRegistrationRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<CongressRegistrationRequest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../main/resources/CongressRegistration.xsd">
  <Congress>
    <CongressId>0</CongressId>
    <CongressName>CongressName</CongressName>
  </Congress>
  <Registrant>
    <FirstName>FirstName</FirstName>
    <MiddleName>MiddleName</MiddleName>
    <LastName>LastName</LastName>
    <Email>Email</Email>
  </Registrant>
</CongressRegistrationRequest>
